# Generated by Django 4.1.6 on 2023-02-02 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('proyecto_empresarial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(db_index=True, max_length=80)),
                ('cargo', models.CharField(max_length=30)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(max_length=2)),
                ('es_lider', models.BooleanField()),
                ('nivel_estudio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.nivelestudio')),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.ocupacion')),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.profesion')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoEmpresarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=60)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('cantidad_empleados', models.IntegerField()),
                ('facturacion_mensual_aprox', models.IntegerField()),
                ('productos', models.CharField(max_length=1000)),
                ('servicios', models.CharField(max_length=1000)),
                ('tipo_mercado', models.CharField(max_length=5)),
                ('numero_integrantes', models.SmallIntegerField()),
                ('actividad_economica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_empresarial.actividadeconomica')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_empresarial.etapaproyecto')),
                ('persona_contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto_empresarial.integrante')),
            ],
        ),
        migrations.AddField(
            model_name='integrante',
            name='proyecto_empresarial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_empresarial.proyectoempresarial'),
        ),
    ]
