# Generated by Django 4.1.6 on 2023-02-02 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_empresarial', '0002_integrante_proyectoempresarial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=11)),
                ('razon_social', models.CharField(max_length=30)),
                ('fecha_formalizacion', models.CharField(max_length=30)),
                ('cubrimiento', models.CharField(max_length=1)),
                ('proyecto_empresarial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_empresarial.proyectoempresarial')),
                ('tamano_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_empresarial.tamanoempresa')),
                ('tipo_sociedad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_empresarial.tiposociedad')),
            ],
        ),
    ]
