# Generated by Django 4.1.6 on 2023-02-02 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_empresarial', '0003_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quien_ayudara', models.CharField(max_length=1000)),
                ('como_hace', models.CharField(max_length=1000)),
                ('que_haces', models.CharField(max_length=1000)),
                ('como_interactuas', models.CharField(max_length=1000)),
                ('a_quien_ayudas', models.CharField(max_length=1000)),
                ('como_alcanzarlos', models.CharField(max_length=1000)),
                ('cual_sera_costo', models.CharField(max_length=1000)),
                ('cuanto_ganaras', models.CharField(max_length=1000)),
                ('proyecto_empresarial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_empresarial.proyectoempresarial')),
            ],
        ),
    ]
