# Generated by Django 4.1.6 on 2023-02-02 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocalizacion', '0001_initial'),
        ('proyecto_empresarial', '0004_modelonegocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionContactoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=15)),
                ('celular2', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=60)),
                ('instagram', models.CharField(max_length=60)),
                ('facebook', models.CharField(max_length=60)),
                ('otro_barrio', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('barrio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocalizacion.barrio')),
                ('departamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocalizacion.departamento')),
                ('division_territorial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocalizacion.divisionterritorial')),
                ('municipio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocalizacion.municipio')),
                ('pais_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocalizacion.pais')),
                ('proyecto_empresarial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_empresarial.proyectoempresarial')),
            ],
        ),
    ]
